### ISSUE TITLE
How can i bind event to a chart

### ISSUE THREAD

**Issue by teamrun** [reactjs/react-chartjs#10]
in chart.js doc, [BarChart prototype-methods](http://www.chartjs.org/docs/#bar-chart-prototype-methods), i can bind click event listener to the canvas and get the clicked bar via _chart instance_'s methods. But in react, in this component, i can not access to the chart instance, even i do not know where is the canvas is... so how can i bind event listener and get the bar clicked?

**Comment by jhudson8** [comment]
I've released 0.5.0 which has 2 additional methods on all chart components
- **_getChart**_: return the chartjs instance
- **_getCanvass**_: return the canvass DOM element

**Comment by teamrun** [comment]
Yeah, thanks a lot, this solves my problem~

**Comment by dandonahoe** [comment]
I'm somewhat new to ReactJS and can't seem to get ```getChart``` working. 

Could you post an example?
