### ISSUE TITLE
Upgrade to chart.js 2.0

### ISSUE THREAD

**Issue by sinaler** [reactjs/react-chartjs#102]
When can we have support for Chart.js 2.0?
since this morning I start getting the error below with latest package updates: 

`core.js:60 Uncaught TypeError: [chartType] is not a function` at
`var chart = new Chart(ctx)[chartType](nextProps.data, nextProps.options || {});`

thank you so much!

**Comment by leighghunt** [comment]
Hi @sercaninaler - see #84 too for similar issue. And perhaps not entirely unrelated to #100 that I'm experiencing myself, still with v2.

**Comment by sinaler** [comment]
Hi and sorry for duplicate issue. closing and following over there.
