### ISSUE TITLE
core.js:60 Uncaught TypeError: (intermediate value)[chartType] is not a function

### ISSUE THREAD

**Issue by dhruv004** [reactjs/react-chartjs#103]
Hi I am trying to implement this in my project.I am new to chartjs as well.
I get the following error.

`core.js:60 Uncaught TypeError: (intermediate value)[chartType] is not a function`
`core.js:46 Uncaught TypeError: Cannot read property 'name' of undefined`

I don't know what is causing this.Does this have anything to do with the versions.Any help would be good.

**Comment by dhruv004** [comment]
Its a version Issue sorry.

**Comment by ayozebarrera** [comment]
@dhruv004 how you resolve this? I'm having the same issue

**Comment by dhruv004** [comment]
@ayozebarrera the latest chartjs version is 2.0 and react-chartjs is not yet compatible with it.Just install   a previous version of chartjs for now.

**Comment by ayozebarrera** [comment]
I see, thankyou! I'll try

**Comment by ayozebarrera** [comment]
Maybe @jhudson8 should put it on README... 

```
>= 1.1.1 & < 2.0
```

**Comment by Statfine** [comment]
@ayozebarrera  i have change "chart.js": "^1.1.0", to 1.1.1; but has the same error!
