### ISSUE TITLE
Set Global Property to Responsive or Canvass Width to 100%

### ISSUE THREAD

**Issue by switmac** [reactjs/react-chartjs#118]
Hello, 

Is there anyway for me to set the canvass width to 100% to make it responsive?
Or how can I set the global property to responsive using ecma6 in React.

Here is my sample usage of the API. 

``` javascript
import {Line} from 'react-chartjs';

class Chart extends Component {
    render(){
         return (
             <div className="chart">
                 <Line data={this.state.data}  options={this.state.options} width={this.props.width} height={this.props.height}/>
              </div>
         );
    }
}
```

**Comment by rublev** [comment]
Set the width on your graph container, then set the width of your canvas element to 100% using css `width: 100% !important`.

Set these global chart options to:

```
responsive: true,
maintainAspectRatio: false,
```

**Comment by jsina** [comment]
I've done it with this code. although I've use the chart.js for showing on `WebView` on my application.
` <canvas style="width: 100% !important;height: auto !important;" id="canvas">`
