### ISSUE TITLE
How to use getBarsAtEvent?

### ISSUE THREAD

**Issue by n3ssi3** [reactjs/react-chartjs#125]
Hey

I am trying to add an onClick function for my Charts (f.e. BarChart).
How can I access functions from BarChart when using BarChart only as a component? 

My current code snippet:

``` javascript
onClickFunction: function (e) {
    // let activeBars = (e.type !== 'mouseout') ? this.getBarsAtEvent(e) : [];
},

render: function () {
    return (<BarChart ref="charts1" data={data} options={chartOptions} onClick={this.onClickFunction}/>)
}
```

Obviously "this" in my onclick function is undefined, but there should be a way to access that, shouldn't it?

Thanks,
Vanessa

**Comment by ledsun** [comment]
You can access the chart by `this.refs.chart1`.

Like:

``` js
onClickFunction: function (e) {
    let activeBars = this.refs.charts1.getBarsAtEvent(e);
},
```

**Comment by n3ssi3** [comment]
Super, thanks
