### ISSUE TITLE
LineChart will not change colors

### ISSUE THREAD

**Issue by rnaar** [reactjs/react-chartjs#134]
The line chart is rendering with a solid gray fill color, and will not change with varying options for background color in dataset, or when the fill is set to false. Data object in dataset that is being used is the same as the one in the documentation for chartjs under 'Data Structure' for LineChart.

http://www.chartjs.org/docs/#line-chart-data-structure

**Comment by ledsun** [comment]
The react-chartjs is not support Chart.js V2.

If you use Chart.js v1.1.1, that has not a `backgroundColor` option.
Please refer [documents of Chart.js v1.1.1](https://github.com/chartjs/Chart.js/blob/v1.1.1/docs/02-Bar-Chart.md).

If you want to use Chart.js V2, please try `chartjs-v2` branch.

```
npm i react-chartjs@git://github.com/reactjs/react-chartjs.git#chartjs-v2
```

**Comment by janakact** [comment]
@ledsun 
Thanks a lot :+1:

**Comment by Jareechang** [comment]
closing due to issue being differences in documentation.
