### ISSUE TITLE
Unkind urls of the Chart.js document in the READEME

### ISSUE THREAD

**Issue by ledsun** [reactjs/react-chartjs#137]
Many people were confused about the document of the Chart.js by READEME:
- #136 
- #134 
- #124 

I propose to correct urls in the section `Example Usage` on the README.
I think https://github.com/chartjs/Chart.js/tree/v1.1.1/docs is good for new url. 

If you need, I will create a pull request.

**Comment by Jareechang** [comment]
This should be updated now. Closing issue.
