### ISSUE TITLE
GetChart not working

### ISSUE THREAD

**Issue by nesbtesh** [reactjs/react-chartjs#140]
Hi, I am trying to reference the chartjs object to do something like this:
`
onClick: function(e){
    var chart = getChart();
    chart.getElementAtEvent(evt); 
}
`

Any ideas why is not working?

**Comment by ledsun** [comment]
You can get an instance of react-chartjs component by using `ref` like:

``` js
const App = React.createClass({
  handleClick(e) {
    const chart = this.Bar.getChart()
    chart.getElementAtEvent(e)
  },
  render() {
    return (<Bar data={chartData} options={chartOption} onClick={this.handleClick} ref={(ref) => this.Bar = ref}/>)
  }
})
```
