### ISSUE TITLE
Support for .addData and .removeData?

### ISSUE THREAD

**Issue by sklise** [reactjs/react-chartjs#15]
I'm trying to use this library to re-use a graph that can switch from 7 items to 30 items. It seems that whenever the number of items changes I get `Uncaught TypeError: Cannot set property 'value' of undefined` This happens every time the number of values to be charted changes.

If I have the `redraw` option enabled then these errors do not occur. With the `redraw` I would need to set `animation: false` otherwise I get some flickering in the chart.

Is this expected, or, am I probably implementing the graphs in the wrong way?

Thanks! _this project is awesome_

**Comment by jhudson8** [comment]
can you make a unit test or a jsbin or something - I'm not actively using react-chartjs at the moment because I got caught up in another project but I'll have a look

**Comment by sklise** [comment]
ah, in trying to figure out how to recreate the issue with jsfiddle/bin I found what the problem was, and it was my code. I had a `chartData` object with `{datasets: {key1: {...}, key2: {...}}` instead of `{datasets: [{...},{...}]`

Which works fine except for when `updatePoints()` was called.

Thank you for your time!
