### ISSUE TITLE
Horizontal Bar chart

### ISSUE THREAD

**Issue by openmohan** [reactjs/react-chartjs#159]
render(){
var ctx= document.getElementById("test")
var myBarChart = new Chart(ctx, {
    type: 'horizontalBar',
    data: data,
    options: options
}); 
}
return (<div id="test"></div>)

Even though I give this , the code in the component get executed before the document gets loaded . So "ctx" will be null . I need to use without Jquery plugin.

**Comment by ashutoshjha1409** [comment]
Initialise chart in componentDidMount()

For E.g

`componentDidMount(){
	var ctx= document.getElementById("test");
		var myBarChart = new Chart(ctx, {
			type: 'horizontalBar',
			data: data,
			options: options
		});
	}
}
`

Sorry, can't indent properly

**Comment by openmohan** [comment]
Thanks @ashutoshjha1409  . Forgot that completely

**Comment by Jareechang** [comment]
This will be available in `react-chartjs 2.0` once we have a stable version. Please see branch `chartjs-v2`.
