### ISSUE TITLE
How to call getChart and getCanvass

### ISSUE THREAD

**Issue by dandonahoe** [reactjs/react-chartjs#16]
Issue #10 mentions two methods:
- **getChart**: return the chartjs instance
- **getCanvass**: return the canvass DOM element

which expose the internal ChartJS object, but I'm not sure how to actually call those. Could someone provide a quick example of invoking either of those methods?

**Comment by heybenchen** [comment]
Here's an example using getCanvass to bind a click on a point on the chart:
https://gist.github.com/superchoob/08329444afe9c0f33afc

**Comment by dandonahoe** [comment]
Huge thanks @superchoob

**Comment by ledsun** [comment]
I cannot read an example at:
https://gist.github.com/superchoob/08329444afe9c0f33afc

**Comment by heybenchen** [comment]
@ledsun I changed my username, try https://gist.github.com/heybenchen/08329444afe9c0f33afc

**Comment by ledsun** [comment]
Thanks a lot @heybenchen
