### ISSUE TITLE
nextProps.data.forEach is not a function

### ISSUE THREAD

**Issue by xtabbas** [reactjs/react-chartjs#164]
Im getting this issue `nextProps.data.forEach is not a function` only in PieChart and DoughnutChart others working just fine

```
var PieChart = require("react-chartjs").Pie;
var DoughnutChart = require("react-chartjs").Doughnut;

var chartData = {
    labels: ["Red", "Blue", "Yellow"],
    datasets: [{ data: [300, 50, 100] }]
};

<PieChart data={chartData} />
```

**Comment by FardinKarimi** [comment]
I can confirm this for Polar Area Chart also.

**Comment by xtabbas** [comment]
@FardinKarimi I solved the issue using react-chartjs-2 which is actively maintain BUT if you want to use this version you have to use chartData as an array with PieChart DoughnutChart etc so something like this should work

```
var chartData = [
    labels: ["Red", "Blue", "Yellow"],
    datasets: [{ data: [300, 50, 100] }]
]
```

**Comment by FardinKarimi** [comment]
@touqeerkhan11 thanks so far. Using chartData didn't help, so I switched to the maintained `react-chartjs-2` and it works well.
