### ISSUE TITLE
Responsive? HAHAHA

### ISSUE THREAD

**Issue by cyllu2** [reactjs/react-chartjs#165]
How does this package have this many stars? Every time you resize or change data, the fucking chart balloons up in size. Setting max-height doesn't work, wrapping in div doesn't work, EVERYTHING comes with a caveat such as labels taking up the majority of the size instead, etc.

Worthless. Piece. Of. Shit.

**Comment by khalednobani** [comment]
@cyllu2 Can you share the screenshots / video ?

**Comment by jorilallo** [comment]
People do open source for the good of their hearts. If you think a library is a piece of ****, keep that to yourself and write a better one. Or better yet, fix the issue. It's issues like this that make people leave open source.

**Comment by cyllu2** [comment]
> It's issues like this that make people leave open source.

Good.

**Comment by austinpray** [comment]
PRs accepted
