### ISSUE TITLE
This project is not working with latest chart.js code (API change)

### ISSUE THREAD

**Issue by a-r-d** [reactjs/react-chartjs#172]
Apparently the latest chart.js has changed their initialization API so that when this line in core is called, initialization fails: 
```
var chart = new Chart(ctx)[chartType](nextProps.data, nextProps.options || {});
```

It seems that version 1.1.1 of chart.js is working fine, not sure when the breaking change went in. The latest version of chart.js is 2.4.0, and it does not work with this project anymore.

**Comment by Jareechang** [comment]
this library is based on specific version of chart.js (1.1.1) and certainly when upgrading to a major version, there will be plenty of deprecations.

**Comment by davidmason** [comment]
@a-r-d the master version is only expected to work with 1.x versions of chartjs. There is a branch for chartjs-v2 but no releases from that branch yet.

We will be working on roadmaps soon, so I think we will look at what is needed to get the v2 branch ready for release.

**Comment by benmccann** [comment]
Please see https://github.com/reactjs/react-chartjs/issues/154. Closing this issue as a duplicate
