### ISSUE TITLE
scatter not working

### ISSUE THREAD

**Issue by jonchoi** [reactjs/react-chartjs#178]
is this a known issue?

error
![image](https://cloud.githubusercontent.com/assets/9872658/24925901/9872cd8a-1eae-11e7-83d0-0ba9a15c1030.png)

data, options
![image](https://cloud.githubusercontent.com/assets/9872658/24925898/93701dec-1eae-11e7-884d-b5b66eef64b7.png)

init
![image](https://cloud.githubusercontent.com/assets/9872658/24925907/a05491d2-1eae-11e7-896e-7c603af68baf.png)

**Comment by jonchoi** [comment]
upgrading to latest chart.js (2.5.0) fixed the issue.

**Comment by guillaumekugener** [comment]
This is still an issue for me having added react-chartjs to my project. Here is the package.json file within project:

```
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "chart.js": "^1.1.1",
    "express": "^4.15.3",
    "moment": "^2.18.1",
    "react": "^15.5.4",
    "react-chartjs": "^0.8.0",
    "react-date-picker": "^5.3.28",
    "react-datepicker": "^0.46.0",
    "react-dom": "^15.5.4",
    "react-transition-group": "^1.1.3"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babelify": "^7.3.0",
    "react-scripts": "0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```
I am using the same code as above to try to generate a line plot and am getting the same error.

Thanks!
