### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by ljknight** [reactjs/react-chartjs#183]
From the console warning: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by deoxxa** [comment]
Annnd now it's completely gone. The PR that references this issue was merged into the v2 branch, which doesn't seem to be the same as what's on npm.

**Comment by sabbul786** [comment]
Good

**Comment by yankopetrov** [comment]
1 month late and still not fixed :( That's bad sign.

**Comment by austinpray** [comment]
Fix it on master -> submit a PR -> I'll merge it and make an npm release

**Comment by yankopetrov** [comment]
There is already PR about that https://github.com/reactjs/react-chartjs/pull/192

**Comment by benmccann** [comment]
Seems like the PR to fix this was merged
