### ISSUE TITLE
Display Legends in Pie graph using react chartjs1

### ISSUE THREAD

**Issue by michaelroevievictoria** [reactjs/react-chartjs#190]
Im using "react-chartjs": "^0.7.3", and I want to display my legends using Pie Graph and my code looks like this. The pieConfig the configuration that I want to display, and the this.state.dataPie is my default

```
pieConfig:{
   //Boolean - Whether we should show a stroke on each segment
   segmentShowStroke: true,

   //String - The colour of each segment stroke
   segmentStrokeColor: "#fff",

   //Number - The width of each segment stroke
   segmentStrokeWidth: 2,

   //Number - The percentage of the chart that we cut out of the middle
   percentageInnerCutout: 0, // This is 0 for Pie charts

   //Number - Amount of animation steps
   animationSteps: 0,

   //String - Animation easing effect
   animationEasing: "easeOutBounce",

   //Boolean - Whether we animate the rotation of the Doughnut
   animateRotate: false,

   //Boolean - Whether we animate scaling the Doughnut from the centre
   animateScale: false,

   fullWidth: true,

   //String - A legend template
   legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].lineColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>",

   legend: {
      display: true,
    },
 }
}

    this.state = {
       dataPie:[{
         value: 300,
         color: "#F7464A",
         highlight: "#FF5A5E",
         label: "Red"
       }, {
         value: 50,
         color: "#46BFBD",
         highlight: "#5AD3D1",
         label: "Green"
       }, {
         value: 100,
         color: "#FDB45C",
         highlight: "#FFC870",
         label: "Yellow"
       }]
}


<Col xs={12}>
         <Paper style={{padding: '30px 20px', marginBottom: 35}} zDepth={2} rounded={false}>
           <Row style={{margin: '40px 40px 40px 40px'}}>
             <Col xs={12}>

                 <Pie
                   data={this.state.dataPie}
                   options={this.props.pieConfig}
                   width="1000"
                   height="556"
                 />

             </Col>
           </Row>
         </Paper>
       </Col>

```I hope someone who could help me to display the legends in react-chartjs 1

**Comment by joshi-mehul** [comment]
Hi @michaelroevievictoria can you provide fiddle? I would love to provide fix for this.

**Comment by michaelroevievictoria** [comment]
Hi @joshi-mehul thanks for the help Pal! But now I finally figure it out how to do it.. sorry if I don't have jsfiddle code: but here's some code snippets (react-js, babel, ES6)

import { Pie } from 'react-chartjs'
 
pieConfig:{
       //Boolean - Whether we should show a stroke on each segment
       segmentShowStroke: true,

       //String - The colour of each segment stroke
       segmentStrokeColor: "#FFF",

       //Number - The width of each segment stroke
       segmentStrokeWidth: 1,

       //Number - Amount of animation steps
       animationSteps: 0,

       //String - Animation easing effect
       animationEasing: "easeOutBounce",

       //Boolean - Whether we animate the rotation of the Doughnut
       animateRotate: true,

       //Boolean - Whether we animate scaling the Doughnut from the centre
       animateScale: false,

       fullWidth: true,

       responsive: true,

       showInLegend: true,

        maintainAspectRatio: true,

        legendTemplate: "<ul style=\" display: inline;\" className=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li style=\"float: left; clear: both; list-style: none;\"><div className=\"indicator_box\" style=\"background-color:<%=segments[i].fillColor%>; padding: 5px ; margin: 8px 10px 5px 10px; display: block; float: left; \"></div><span style=\"font-size: 1.250em; word-wrap: break-word;\"><%if(segments[i].label){%><%=segments[i].label%><%}%></span></li><%}%></ul>",
     }
   }



 this.state = {
      dataLine: {
        labels: [''],
        datasets: [{
          label: "My First dataset",
          fillColor: "rgba(220,220,220,0.2)",
          strokeColor: "rgba(220,220,220,1)",
          pointColor: "rgba(220,220,220,1)",
          pointStrokeColor: "#fff",
          pointHighlightFill: "#fff",
          pointHighlightStroke: "rgba(220,220,220,1)",
          data: [0]
        }],
      }
     }
}



  onAnalyticsStoreChange = () => {
    let data = AnalyticsStore.getFundrAnalytics()
    this.setState({
      data: data,
      dataLine: this.constructLineChartData(
        _.get(_.find(this.constants.DATE_RANGE_DROPDOWN, {value: this.state.selectedDateRange}), 'label', '') + " Units Sold",
        _.get(data, 'unitsSoldData'),
        _.get(data, 'comparedUnitsSoldData') ? "Previous Units Sold" : null,
        _.get(data, 'comparedUnitsSoldData')
      ),
      dataPie: this.constructPieChartData(
        _.get(data, 'categoryUnitsSoldData', [{
          unitsSold: 0,
          category: ''
        }])
      )
    }, () => {
      this.setState({

        dataPieLegendHTML: this.refs.pieChart.generateLegend()  // I TRY TO CALL FROM THE react-chartjs nodes
      })
    })
  }



```
<Col xs={8 } style={{ marginTop: '3%' }}>
                      <Pie ref='pieChart'
                        redraw
                        data={this.state.dataPie}
                        options={this.props.pieConfig}
                        generateLegend={true}
                      />
                    </Col>
                    <Col xs={4}>
                      <div dangerouslySetInnerHTML={{__html: this.state.dataPieLegendHTML}}/>
                    </Col>

```

**Comment by joshi-mehul** [comment]
@michaelroevievictoria great, happy that you've fixed the issue.

**Comment by joshi-mehul** [comment]
@michaelroevievictoria please close the issue now.
