### ISSUE TITLE
v2 Abandoned?

### ISSUE THREAD

**Issue by nabilfreeman** [reactjs/react-chartjs#191]
Is this repo still active for Chartjs 2?

I found a more active repo here:

https://github.com/jerairrest/react-chartjs-2

... and am trying to understand which library is best to use.

**Comment by liorocks** [comment]
Same here. Need for the upcoming project and looking for the best solution.

**Comment by benmccann** [comment]
Please see https://github.com/reactjs/react-chartjs/issues/154. Closing this issue as a duplicate
