### ISSUE TITLE
Compatibility with version 16 of react

### ISSUE THREAD

**Issue by cardacci** [reactjs/react-chartjs#195]
With the new React update I get some errors, since they have removed methods from the React core such as propTypes and createClass

Do you plan to update this library to make it compatible?

**Comment by rambabusaravanan** [comment]
Yes, I'm also facing issue the error in React 16
> TypeError: React.createClass is not a function

Any plans to migrate ..?

**Comment by rgranger** [comment]
+1 for visibility

**Comment by savacristian** [comment]
+1

**Comment by DiViNiZe** [comment]
++

**Comment by pnicorelli** [comment]
+1

**Comment by austinpray** [comment]
You guys should review this: https://github.com/reactjs/react-chartjs/pull/192

**Comment by LadyInnogen** [comment]
+1

**Comment by gauravkalyan** [comment]
+1

**Comment by zhaozhouyang** [comment]
+1

**Comment by nettiopsu** [comment]
+1

**Comment by austinpray** [comment]
If anyone wants to take a crack at it I am more than happy to give you contributor access.

**Comment by saikatbhattacharya** [comment]
May I try to resolve that? Give me access please.

**Comment by austinpray** [comment]
@saikatbhattacharya you got it! go for it

**Comment by benmccann** [comment]
@DylanMunyard should this be closed now that https://github.com/reactjs/react-chartjs/pull/192 has been merged?

**Comment by benmccann** [comment]
Closing since https://github.com/reactjs/react-chartjs/pull/192 has been merged to fix this
