### ISSUE TITLE
publish new version on npm, bower

### ISSUE THREAD

**Issue by erictse** [reactjs/react-chartjs#2]
that has commit https://github.com/jhudson8/react-chartjs/commit/ad796702f52d459812922b06252a13b4be2129ad

thanks

**Comment by jhudson8** [comment]
v0.1.2

**Comment by andrinealver** [comment]
@jhudson8 you may have released `v0.1.2` to npm/bower but it's not actually got the commit in. Likewise, the built and minified versions in the repo don't actually have the code in!

**Comment by jhudson8** [comment]
doh!  I must have forgotten to pull down your commit.  I just tagged v0.1.3
