### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by HPaulos** [reactjs/react-chartjs#201]
As React.createClass is deprecated method it needs to be resolved. It can be resolved with use of library 'create-react-class'. Please resolve it.

**Comment by blizzo521** [comment]
With React `16.2.0` I get an error rather than a deprecation warning:
`Uncaught TypeError: React.createClass is not a function`

**Comment by DylanPMunyard** [comment]
Hello - this has just been resolved, https://github.com/reactjs/react-chartjs/pull/192
