### ISSUE TITLE
access to npm

### ISSUE THREAD

**Issue by Jareechang** [reactjs/react-chartjs#209]
@austinpray, @jerairrest, @benmccann when one of you guys get a chance could you please provide access to npm package. I'd like to start adding some changes, and publishing them. 

**my account:** https://www.npmjs.com/~jareechang

Thanks.

**Comment by benmccann** [comment]
@Jareechang what do you think the strategy should be? Should we just replace this code base with @jerairrest's [react-chartjs-2](https://github.com/jerairrest/react-chartjs-2)? I know Chart.js pretty well, but not React too well. It seems like these two codebases take somewhat different approaches, but I don't know if there's anything that one does particularly stronger than the other

**Comment by jerairrest** [comment]
I'm also fine transferring the entire project to the reactjs project instead of taking the multiple branch approach.

For chart.js 1 you would use reactjs/react-chartjs
For chart.js 2 you would use reactjs/react-chartjs-2

Thoughts?

**Comment by benmccann** [comment]
What would happen when we have a Chart.js 3 release in that case? I'm not sure we'll want to make a new repo for every major release. Potentially we could rename this repo to react-chartjs-1 and rename react-chartjs-2 to just react-chartjs

I guess the other question is do we still want to actively maintain code supporting Chart.js 1.x? I personally am not very interested in that and would like to encourage people to move to Chart.js 2.x

**Comment by jerairrest** [comment]
That is a valid point. If chartjs is not maintaining both version I would say deprecating v1 is probably the best idea.

**Comment by benmccann** [comment]
No further updates are being made to Chart.js 1.x, so let's deprecate v1 as you suggest

**Comment by Jareechang** [comment]
@benmccann and @jerairrest, I agree with deprecating v1. `Chart.js 2.x` provides all feature that `Chart.js 1.x` provides and more. 

Also, judging from the issues created on here, many people are asking for `Chart.js 2.x` support.

## Branching 

A good starting point is integrating the two repos - **react-chartjs** and **react-chartjs-2**.

I think it would make sense for master branch to support **latest** version of Chart.js just to avoid any confusion. 

Bulk of the issues in this repo is due to users referring to the wrong documentation of Chart.js due to different version. 

I am more than happy to help support and maintain once we've integrated 😄

**Comment by austinpray** [comment]
Hey! Sorry for 6 day turnaround but I went ahead and added you.

![image](https://user-images.githubusercontent.com/2192970/35188488-a80c4190-fdfb-11e7-80ee-d042a8033555.png)

**Comment by benmccann** [comment]
I agree that the master should support Chart.js 2.x

Closing this issue since the npm access has been resolved
