### ISSUE TITLE
react-native support ? 

### ISSUE THREAD

**Issue by mydearxym** [reactjs/react-chartjs#21]
amazing work!
is this component support react-native?

**Comment by jhudson8** [comment]
I really don't know if react-native supports canvas.  Try it out and let me know

**Comment by joshhornby** [comment]
@mydearxym You could try https://www.npmjs.com/package/react-native-canvas but it seems to be quite alpha.

**Comment by acomito** [comment]
seems this is still going?

https://www.npmjs.com/package/react-native-canvas

**Comment by geminiyellow** [comment]
working ?
