### ISSUE TITLE
no full example? where is chartData and chartOptions?

### ISSUE THREAD

**Issue by peterremote1980** [reactjs/react-chartjs#218]
no full example? where is chartData and chartOptions?

**Comment by AnisDerbel** [comment]
+1

**Comment by ghost** [comment]
I had this problem. 

If you download [React Developer Tools for Chrome ](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en) You can inspect the chart and see its props.

**Comment by wkolcz-UMHS** [comment]
Not sure if this helps but if you got to the chartjs site, you can copy the examples to produce a chart and then follow the core libraries standards.

For example: a donut chart, https://github.com/chartjs/Chart.js/blob/v1.1.1/docs/05-Pie-Doughnut-Chart.md and you can copy the array of objects in the Data structure section (exactly) into the chartData variable and the Chart options array into a charOptions variable and use it as the value of the props.

**Comment by peterremote1980** [comment]
thx

**Comment by alondahari** [comment]
I think it would be very helpful to include those in the example page, and also in the repo (under examples folder).
@peterremote1980 IMO this issue is still open...
