### ISSUE TITLE
Redraw and nextProps

### ISSUE THREAD

**Issue by bultas** [reactjs/react-chartjs#22]
In my opinion, should be in Core.js/componentWillReceiveProps `nextProps.redraw` instead of `this.props.redraw`, 
With nextProps.redraw you enable to choose how user want draw the chart in next update cycle (redraw:false with new metrics or redraw:true with new labels,..). 
But with this.props.redraw you can affect only second update cycle, which is not so flexible and you can not redraw chart instantly when you need it.

Is there some point why it has to be this.props.redraw or can I create pull request?

**Comment by jhudson8** [comment]
sounds like a better approach. feel free to create a PR.  Thanks

**Comment by ghost** [comment]
Thanks a lot bultas! I was having this weird bug where the chart redraws only in the second update.
