### ISSUE TITLE
not supporting percent in width

### ISSUE THREAD

**Issue by RZsam** [reactjs/react-chartjs#222]
`<Line width="100%"  height="250"  />` It's expected to set width 100% but when it rendered width is 100px.
    how to set width to 100% of parent's width?

**Comment by agent3bood** [comment]
Setting width of a canvas element is not an option (it is not a possible even in plain html)
Reade more here https://www.w3schools.com/tags/att_canvas_width.asp

**Comment by RZsam** [comment]
@agent3bood thank you
