### ISSUE TITLE
Support community extensions

### ISSUE THREAD

**Issue by joelving** [reactjs/react-chartjs#27]
Chart.js makes it easy to extend the range of chart types available, but react-chartjs hides these by hard-coding the chart types available.

I understand it is rather trivial to do this yourself when building using node and Gulp, and it wasn't hard to modify the standalone build either, but it would be nice not to have to modify the source every time you include a custom chart, if for no other reason than to ease upgrading.

**Comment by joshhornby** [comment]
Agreed @joelving. If you wish to submit a PR I will take a look and we can work out a solution.

**Comment by joelving** [comment]
I was obviously too hasty in my review of the source. Your solution of exposing the createClass method is perfectly adequate, and can easily accommodate additional chart types that attaches to the main object.

Big props! :)
