### ISSUE TITLE
AMD/RequireJS Support?

### ISSUE THREAD

**Issue by Huxpro** [reactjs/react-chartjs#30]
Have any idea support AMD?
ChartJS works very well with AMD Loader

Manually add AMD wrapper is annoying

**Comment by Huxpro** [comment]
Well.. after finishing the conversion..

No more RequireJS , I swear...

**Comment by conorhastings** [comment]
according to the docs, only commonjs is supported, https://github.com/jhudson8/react-chartjs

**Comment by jhudson8** [comment]
Thanks.  I meant to respond but didn't get to it.  Only commonjs is supported.  There are no plans to support AMD (use http://webpack.github.io/)
