### ISSUE TITLE
Error when using webpack-dev-server with indication url

### ISSUE THREAD

**Issue by dennisjac** [reactjs/react-chartjs#39]
I've run into a problem when using react-chartjs in the context of webpack-dev-server but only when using the indication url. When I use the url "http://localhost:8080/" to connect to the dev-server the doughnut I'm trying to render works fine but if I use "http://localhost:8080/webpack-dev-server/" the page itself renders fine but there is only empty space where the doughnut should be and in the console I see the following error: "TypeError: document.defaultView.getComputedStyle(...) is null".
Any ideas what is going on?

**Comment by joshhornby** [comment]
Is this still an issue? Seems like a webpack issue more than react-chartjs.
