### ISSUE TITLE
Question: With Advanced Usage

### ISSUE THREAD

**Issue by JGSolutions** [reactjs/react-chartjs#43]
How can I use this method?

From the chart.js site:
var myLineChart = new Chart(ctx).Line(data);
myLineChart.generateLegend();

Since react.js is rendering the pie chart.
<PieChart ref="pieChart" data={data} options={chartOptions} />

**Comment by Dallas62** [comment]
You can use `.getChart()` on the chart element then you have the `myLineChart` instance.

```
var ChartElement = (<LineChart data={data} />);

vart chart = ChartElement.getChart();

chart.generateLegend();
```

**Comment by queimadus** [comment]
@Dallas62, does your example still work in the latest react version?

**Comment by Dallas62** [comment]
@queimadus I'm using react 0.13.3 and it seems to work. But the legend isn't a ReactElement.

**Comment by queimadus** [comment]
@Dallas62, my question specifically is if you can access the `getChart()` method before the `ChartElement` is rendered by the `render` method.

I managed to access the `chart` by rendering the `ChartElement` with a `ref` and then doing `this.refs.chart.state.getChart()` in the `componentDidMount` e.g..

How are you accessing the chart? Could you give an example?

Ideally, I'd like to render the `ChartElement` and the `generateLegend()` html right away in the `render()` function without having to use `componentDidMount` and using the approach described above.

**Comment by Dallas62** [comment]
@queimadus I do not use `generateLegend()` in my case, I generate the legend myself.

I just answered to the question: How can I use this method?

**Comment by queimadus** [comment]
@Dallas62 so you don't access the underlying `chart` object from _chart.js_ encapsulated in the `ChartElement` at all.

You generate the legend from the `data` you pass as props to the `ChartElement`. Is that it?

**Comment by Dallas62** [comment]
Exactly
