### ISSUE TITLE
React 0.14 compatiblity

### ISSUE THREAD

**Issue by dmr** [reactjs/react-chartjs#47]
Hi everyone,
two things I had to change to make react-chart compatible with the latest reactjs 0.14 beta:
1.  I removed the `getDOMNode()` from `this.refs.canvass.getDOMNode()` core.js line 66.
2. `var el = this.getDOMNode();`--> `var ReactDOM = require('react-dom'); ReactDOM.findDOMNode(this);`

react-chartjs is working fine in reactjs 0.14 beta after that :)
Just wanted to let you know in case anyone is interested.

**Comment by asci** [comment]
any pull request, fork?

**Comment by dmr** [comment]
Sure, https://github.com/jhudson8/react-chartjs/pull/48.

**Comment by sspross** [comment]
+1

**Comment by mgibeau** [comment]
I'm also interested in having this merged, but I believe to be safe the _peerDependencies_ should be updated to:

```
"peerDependencies": {
    "react": "^0.14.0",
    "react-dom": "^0.14.0",
    "chart.js": "*"
}
```

**Comment by dmr** [comment]
@mgibeau Yes, I also think peerDependencies is the way to go here! --> #48

**Comment by gustavoschmidt** [comment]
+1

**Comment by naugtur** [comment]
@dmr peerDependencies are deprecated and will not work anymore in npm v3, which will be coming to node v4 during the LTS period and is already the stable version - you get it when you `npm install npm`

**Comment by mgibeau** [comment]
@naugtur They are not being deprecated, they are simply no longer being installed automatically. They still work in npm 3, as long as you install them manually, which is completely fine and makes sense in the context of plugins such as chartjs.

**Comment by naugtur** [comment]
If you're aware of this, it's cool.

btw. is this project alive? I'm wondering if I should switch to rc-chartjs, which is more up-to-date

**Comment by joshhornby** [comment]
https://github.com/jhudson8/react-chartjs/pull/59
