### ISSUE TITLE
React and Chart.js are not peerDependencies

### ISSUE THREAD

**Issue by apaleslimghost** [reactjs/react-chartjs#51]
`peerDependencies` aren't things you `require`, they're things that your module works alongside of (e.g. Grunt plugins have Grunt as a `peerDependency`). Moreover, since npm 3.0, they're not installed automatically when you install a module.

Since you `require` React and Chart.js, they're regular `dependencies`. You should move them to `dependencies` in `package.json` and give them version constraints (e.g. this library doesn't yet work with React 0.14, so in the `dependencies` hash it should have `"react": "<=0.13"`).

**Comment by raylenmargono** [comment]
hello is this a response to my issue?

**Comment by apaleslimghost** [comment]
No?

**Comment by joshhornby** [comment]
Feel free to submit a PR for this.

**Comment by jxm262** [comment]
@joshhornby  I have a bit of free time today.  Will try to submit a PR soon

**Comment by austinpray** [comment]
this is fixed

**Comment by apaleslimghost** [comment]
Unless I'm missing something, [no, it's not](https://github.com/jhudson8/react-chartjs/blob/e090b90e2569e4a74f4c13228005db453b7cadea/package.json#L29-L33).
