### ISSUE TITLE
ES6 example?

### ISSUE THREAD

**Issue by ararog** [reactjs/react-chartjs#61]
Hi,

I'm trying to make use of bar chart in a React app using ES6/Babel, but no matter what I try I'm always getting the following error:

Uncaught TypeError: Cannot read property 'Chart' of undefined

Anyone had this issue before?

**Comment by ararog** [comment]
In fact this is a webpack related issue, I solved by injection window into module using webpack's import-loader as described here:

http://webpack.github.io/docs/shimming-modules.html#importing

**Comment by austinpray** [comment]
Can you post your full file? ES6 Works fine for me.
