### ISSUE TITLE
PieChart.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.

### ISSUE THREAD

**Issue by dodo360** [reactjs/react-chartjs#64]

**Comment by joshhornby** [comment]
Please submit a PR and I will merge.

**Comment by kasperfilstrup** [comment]
Hi @joshhornby . I saw you accepted the pull request with the fix for this, but it isn't present when `npm install react-chartjs`. Any idea when this will get pushed to npm? (or any tips to how I can get it with npm until it is "published"?) :-)

**Comment by slavovojacek** [comment]
@kasperwf :+1:

**Comment by joshhornby** [comment]
@kasperwf https://docs.npmjs.com/files/package.json#repository Should do the trick.

@jhudson8 Can you update the npm version please?

**Comment by kasperfilstrup** [comment]
Great @joshhornby - thanks a lot! :-D

It turns out it's as simple as changing 
`"react-chartjs": "^0.6.0"` 
to 
`"react-chartjs": "jhudson8/react-chartjs",`
in package.json

[GitHub urls](https://docs.npmjs.com/files/package.json#github-urls)

**Comment by pkibbey** [comment]
It looks like the PR was merged, but the files in dist were not rebuilt, so I'm still getting the same getDOMNode error.

**Comment by underwater** [comment]
It appears that the dist folder is 9 months old still, is it possible to do that so as to get rid of the various errors I am getting on my dashboard source 
- Warning: DoughnutChart.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead.
  If anyone knows how I can do this myself, any guidance is greatly appreciated

**Comment by pkibbey** [comment]
I'll run the build and dist commands (npm run build, npm run dist) then submit a new pull request... give me a few minutes...

**Comment by pkibbey** [comment]
I'm having network issues, so I can't install the required packages...

Try this
1. clone repo
2. run "npm install" in the directory
3. run "npm run dist"
4. Submit pull request.

that 'should' work.... hopefully.

**Comment by underwater** [comment]
Hi there, thanks for your quick response,
Tried that my side, and getting this
8 info react-chartjs@0.7.3 Failed to exec dist script
9 error react-chartjs@0.7.3 dist: `COMPRESS=1 webpack index.js dist/react-chartjs.min.js`
9 error Exit status 1
10 error Failed at the react-chartjs@0.7.3 dist script.

**Comment by pkibbey** [comment]
I finally managed to get this running locally, and have submitted a pull request ^^

**Comment by teone** [comment]
Looks like it is not available yet on NPM, but works if I set `"react-chartjs": "jhudson8/react-chartjs"` in `package.json`

I just don't feel safe not locking the version.

**Comment by lchngr** [comment]
Can you please push the new version to the npm repo. Thx

**Comment by patrickkempff** [comment]
It looks like the current version (0.7.3) is not yet published on npm. 
@jhudson8 It is possible to push it? thanks.

**Comment by austinpray** [comment]
@patrickkempff I just published the latest version, lemme know if this fixes it

**Comment by suancarloj** [comment]
@austinpray 0.7.3 works for me :) thx
