### ISSUE TITLE
Global chart configuration

### ISSUE THREAD

**Issue by johnnyfreeman** [reactjs/react-chartjs#65]
In chart.js, you can set [global chart configuration](http://www.chartjs.org/docs/#getting-started-global-chart-configuration). How can you do this using `react-chartjs` and browserify?

**Comment by kai23** [comment]
+1 ?

**Comment by palmerj3** [comment]
You could define a singleton export with the default options then myOptions = Object.assign({}, mySingleton, { override1: foo, override2: bar});

**Comment by austinpray** [comment]
what @palmerj3 said
