### ISSUE TITLE
Latest version not available on npmjs.com

### ISSUE THREAD

**Issue by sebprunier** [reactjs/react-chartjs#66]
Hi,

The latest version (v0.7.3) is not available on npmjs.com.
Can you upload it please ?

Thx !
Sébastien

**Comment by kojuka** [comment]
same thing here --
npm ERR! No compatible version found: react-chartjs@^0.7.3
npm ERR! Valid install targets:
npm ERR! 0.6.0, 0.5.0, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.3, 0.1.2, 0.1.1, 0.1.0, 0.0.1

**Comment by YPCrumble** [comment]
:+1:

**Comment by MattWilliamsDev** [comment]
:+1:

**Comment by MattWilliamsDev** [comment]
Attempting to get the latest version via NPM to address issue #33.  Will download manually for now, but update is appreciated!

**Comment by joevin22** [comment]
you can to try rc-chartjs,
no warning with react 0.14.x + es6

**Comment by jakemhiller** [comment]
This hasn't been published to NPM in 10 months...

**Comment by austinpray** [comment]
I just shot Joe an email asking him to add me as a collab to the npm package. I can just set travis to publish on tag so it won't be an issue going forward.

**Comment by matheusrocha89** [comment]
:+1: please update

**Comment by andersonba** [comment]
+1

**Comment by austinpray** [comment]
No email from Joe yet

**Comment by patrickkempff** [comment]
+1

**Comment by jhudson8** [comment]
@austinpray adding you now.  Thanks for helping out.

**Comment by sebprunier** [comment]
Seems Ok now !! Latest version available is 0.7.3
Thx

**Comment by austinpray** [comment]
Joe added me, will get travis automatic deploys up soon

**Comment by jhudson8** [comment]
@austinpray I owe you a beer.  thanks for helping out
