### ISSUE TITLE
Can I update chart instead of destroy on componentWillReceiveProps?

### ISSUE THREAD

**Issue by jefffriesen** [reactjs/react-chartjs#7]
I would like to `.update()` the chart when data changes. Right now, passing `data` into the chart component triggers a `.destroy()` and `initializeChart()`, which completely redraws the chart instead of transitioning the data from one point to another. 

I see `update`, `addData` and others in the `extras`, but I couldn't figure out how to call those when new props were passed in.

**Comment by jhudson8** [comment]
Honestly, that area probably needs a little more thought.  I welcome pull requests

**Comment by jefffriesen** [comment]
PR submitted: https://github.com/jhudson8/react-chartjs/pull/8

**Comment by jefffriesen** [comment]
addressed by https://github.com/jhudson8/react-chartjs/pull/8
