### ISSUE TITLE
Does react-chartjs play well with chartjs 2.0.0 beta?

### ISSUE THREAD

**Issue by vsrnth** [reactjs/react-chartjs#71]
Or is it such that react-chartjs is chartjs version agnostic?
 Don't suppose that's the case but what do I know.

**Comment by austinpray** [comment]
Try it out and let us know

**Comment by vsrnth** [comment]
Sure thing.

**Comment by austinpray** [comment]
Thanks!

**Comment by darkone23** [comment]
Tried with react-chartjs 0.7.3 - the answer is no - code that works with current version of react-chartjs does not work with chart.js 2.0 beta, looks like there were some breaking changes in the underlying library.

**Comment by maindi** [comment]
This would be nice, since 2.0.0 supports multiple y-axis

**Comment by austinpray** [comment]
https://github.com/jhudson8/react-chartjs/pull/87
