### ISSUE TITLE
Uncaught TypeError: chart is undefined (Firefox)  / Cannot read property 'name' of undefined (Chrome)

### ISSUE THREAD

**Issue by theo07** [reactjs/react-chartjs#74]
I am generating a number of charts by listening to an event. Every event fired will generate or remove one chart.

Everything works fine but I see this Uncaught TypeError in the console:  chart is undefined (Firefox)  / Cannot read property 'name' of undefined (Chrome).

`module.exports.createClass.classData.componentWillReceiveProps
`

If I add a null check in the library the type error seems to disappear. But I have to say that there is the possibility of using the library wrong. 

Any suggestions/fixes would be greatly appreciated.

Many thanks,
Teo

**Comment by austinpray** [comment]
Can you post the code that you changed to mitigate this error? Odds are this needs to be a PR.
