### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by matrinox** [reactjs/react-chartjs#76]
Is it possible to version the decencies so this package can be used in React 13? Right now any version of react-chartjs, including versions before React 14 was even announced, require React 14.x due to react-dom requiring React 14.x

**Comment by austinpray** [comment]
Here is the break: https://github.com/jhudson8/react-chartjs/commit/29297915b3aa92702b982b7dfdf2103e9390a9cf 

Use 0.6, I suppose. I'm open to bug fixes being backported to 0.6.x if you PR: https://github.com/jhudson8/react-chartjs/tree/0.6
