### ISSUE TITLE
Using the `responsive: true` true option causes errors

### ISSUE THREAD

**Issue by lukebrooker** [reactjs/react-chartjs#9]
Specifically:

```
Uncaught TypeError: Illegal invocation

helpers.cancelAnimFrame.call(root, this.animationFrame);
```

In the Chart.js library itself. I have an idea of why this is happening, but I am still a little too early to react to work it out.

**Comment by jhudson8** [comment]
FWIW, react-chartjs is just a very light wrapper around the chartjs lib.  You don't have enough detail here for me to be able to respond here.  Can you either provide more meaningful details for close this out?

**Comment by jonespen** [comment]
I also get this (using webpack), guess its related to this https://github.com/nnnick/Chart.js/pull/918

**Comment by jhudson8** [comment]
I'm closing the issue here since it is not a react-chartjs issue but rather a chartjs issue.  nothing I can do about it...

**Comment by lukebrooker** [comment]
Thanks, that was the issue that @jonespen mentioned.
