### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by MatthewHerbst** [reactjs/react-chartjs#90]
@joshhornby @jhudson8 is this repo active? There are multiple PRs and issues with no replies for some time. I and others would love to contribute but not if it's not going to go anywhere.

**Comment by joshhornby** [comment]
Hi @MatthewHerbst

I'm afraid I don't use this package in production anymore so don't have the time to commit to the project. You can message @jhudson8 and sure he'd add you as a maintainer.

**Comment by austinpray** [comment]
@MatthewHerbst I'll commit to not letting your PRs sit in limbo :). 

A good place to start would be to help getting this PR in: https://github.com/jhudson8/react-chartjs/pull/87
